# Generated by Django 5.2.7 on 2025-10-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_image_name_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.product'),
        ),
    ]
